<?php

use Aplicacion\Middlewares\AutenticadoMiddleware;
use Aplicacion\Middlewares\EmpresaMiddleware;
use Aplicacion\Controladores\Empresa\PanelEmpresaControlador;
use Aplicacion\Controladores\Empresa\ClientesControlador;
use Aplicacion\Controladores\Empresa\ProductosControlador;
use Aplicacion\Controladores\Empresa\CotizacionesControlador;
use Aplicacion\Controladores\Empresa\ConfiguracionControlador;
use Aplicacion\Controladores\Empresa\UsuariosControlador;
use Aplicacion\Controladores\Empresa\GestionComercialControlador;
use Aplicacion\Controladores\Empresa\DocumentosControlador;
use Aplicacion\Controladores\Empresa\PuntoVentaControlador;
use Aplicacion\Controladores\Empresa\InventarioControlador;
use Aplicacion\Controladores\Empresa\SoporteChatControlador;
use Aplicacion\Controladores\Admin\AdministradoresEmpresasControlador;

$mwEmpresa = [AutenticadoMiddleware::class, EmpresaMiddleware::class];

$enrutador->agregar('GET', '/app/panel', [GestionComercialControlador::class, 'inicio'], $mwEmpresa);
$enrutador->agregar('POST', '/app/panel/iniciar-pago-trial', [GestionComercialControlador::class, 'iniciarPagoPlanTrial'], $mwEmpresa);

$enrutador->agregar('GET', '/app/soporte-chats', [SoporteChatControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('POST', '/app/soporte-chats/crear', [SoporteChatControlador::class, 'crear'], $mwEmpresa);
$enrutador->agregar('GET', '/app/soporte-chats/ver/{id}', [SoporteChatControlador::class, 'ver'], $mwEmpresa);
$enrutador->agregar('GET', '/app/soporte-chats/mensajes/{id}', [SoporteChatControlador::class, 'mensajes'], $mwEmpresa);
$enrutador->agregar('POST', '/app/soporte-chats/responder/{id}', [SoporteChatControlador::class, 'responder'], $mwEmpresa);
$enrutador->agregar('POST', '/app/volver-admin', [AdministradoresEmpresasControlador::class, 'volverPanelAdmin'], $mwEmpresa);
$enrutador->agregar('GET', '/app/clientes', [ClientesControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('GET', '/app/clientes/exportar/excel', [ClientesControlador::class, 'exportarExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/clientes', [ClientesControlador::class, 'guardar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/clientes/crear', [ClientesControlador::class, 'crear'], $mwEmpresa);
$enrutador->agregar('POST', '/app/clientes/crear', [ClientesControlador::class, 'guardar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/clientes/ver/{id}', [ClientesControlador::class, 'ver'], $mwEmpresa);
$enrutador->agregar('GET', '/app/clientes/editar/{id}', [ClientesControlador::class, 'editar'], $mwEmpresa);
$enrutador->agregar('POST', '/app/clientes/editar/{id}', [ClientesControlador::class, 'actualizar'], $mwEmpresa);
$enrutador->agregar('POST', '/app/clientes/eliminar/{id}', [ClientesControlador::class, 'eliminar'], $mwEmpresa);

$enrutador->agregar('GET', '/app/productos', [ProductosControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('GET', '/app/productos/exportar/excel', [ProductosControlador::class, 'exportarExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/productos', [ProductosControlador::class, 'guardar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/productos/crear', [ProductosControlador::class, 'crear'], $mwEmpresa);
$enrutador->agregar('POST', '/app/productos/crear', [ProductosControlador::class, 'guardar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/productos/ver/{id}', [ProductosControlador::class, 'ver'], $mwEmpresa);
$enrutador->agregar('GET', '/app/productos/movimientos/{id}', [ProductosControlador::class, 'movimientos'], $mwEmpresa);
$enrutador->agregar('GET', '/app/productos/editar/{id}', [ProductosControlador::class, 'editar'], $mwEmpresa);
$enrutador->agregar('POST', '/app/productos/editar/{id}', [ProductosControlador::class, 'actualizar'], $mwEmpresa);
$enrutador->agregar('POST', '/app/productos/eliminar/{id}', [ProductosControlador::class, 'eliminar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/productos/carga-masiva', [ProductosControlador::class, 'cargaMasiva'], $mwEmpresa);
$enrutador->agregar('POST', '/app/productos/carga-masiva/productos', [ProductosControlador::class, 'importarProductosMasivo'], $mwEmpresa);
$enrutador->agregar('POST', '/app/productos/carga-masiva/categorias', [ProductosControlador::class, 'importarCategoriasMasivo'], $mwEmpresa);
$enrutador->agregar('GET', '/app/productos/carga-masiva/plantilla/productos', [ProductosControlador::class, 'descargarPlantillaProductosExcel'], $mwEmpresa);
$enrutador->agregar('GET', '/app/productos/carga-masiva/plantilla/categorias', [ProductosControlador::class, 'descargarPlantillaCategoriasExcel'], $mwEmpresa);

$enrutador->agregar('GET', '/app/cotizaciones', [CotizacionesControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('GET', '/app/cotizaciones/exportar-excel', [CotizacionesControlador::class, 'exportarExcel'], $mwEmpresa);
$enrutador->agregar('GET', '/app/cotizaciones/crear', [CotizacionesControlador::class, 'crear'], $mwEmpresa);
$enrutador->agregar('POST', '/app/cotizaciones/crear', [CotizacionesControlador::class, 'guardar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/cotizaciones/editar/{id}', [CotizacionesControlador::class, 'editar'], $mwEmpresa);
$enrutador->agregar('POST', '/app/cotizaciones/editar/{id}', [CotizacionesControlador::class, 'actualizar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/cotizaciones/ver/{id}', [CotizacionesControlador::class, 'ver'], $mwEmpresa);
$enrutador->agregar('GET', '/app/cotizaciones/imprimir/{id}', [CotizacionesControlador::class, 'imprimir'], $mwEmpresa);
$enrutador->agregar('GET', '/app/cotizaciones/pdf/{id}', [CotizacionesControlador::class, 'descargarPdf'], $mwEmpresa);
$enrutador->agregar('POST', '/app/cotizaciones/enviar/{id}', [CotizacionesControlador::class, 'enviar'], $mwEmpresa);
$enrutador->agregar('POST', '/app/cotizaciones/eliminar/{id}', [CotizacionesControlador::class, 'eliminar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/cotizaciones/producto-movimientos/{id}', [CotizacionesControlador::class, 'movimientosProducto'], $mwEmpresa);

$enrutador->agregar('GET', '/app/configuracion', [ConfiguracionControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('POST', '/app/configuracion', [ConfiguracionControlador::class, 'guardar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/logo-empresa', [ConfiguracionControlador::class, 'logoEmpresa'], $mwEmpresa);
$enrutador->agregar('GET', '/app/usuarios', [UsuariosControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('POST', '/app/usuarios', [UsuariosControlador::class, 'guardar'], $mwEmpresa);
$enrutador->agregar('GET', '/app/usuarios/ver/{id}', [UsuariosControlador::class, 'ver'], $mwEmpresa);
$enrutador->agregar('GET', '/app/usuarios/editar/{id}', [UsuariosControlador::class, 'editar'], $mwEmpresa);
$enrutador->agregar('POST', '/app/usuarios/editar/{id}', [UsuariosControlador::class, 'actualizar'], $mwEmpresa);

$enrutador->agregar('GET', '/app/contactos', [GestionComercialControlador::class, 'contactos'], $mwEmpresa);
$enrutador->agregar('GET', '/app/contactos/exportar/excel', [GestionComercialControlador::class, 'exportarContactosExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/contactos', [GestionComercialControlador::class, 'guardarContacto'], $mwEmpresa);

$enrutador->agregar('GET', '/app/contactos/ver/{id}', fn($id) => (new GestionComercialControlador())->verRegistro('contactos', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/contactos/editar/{id}', [GestionComercialControlador::class, 'editarContacto'], $mwEmpresa);
$enrutador->agregar('POST', '/app/contactos/editar/{id}', [GestionComercialControlador::class, 'actualizarContacto'], $mwEmpresa);
$enrutador->agregar('POST', '/app/contactos/eliminar/{id}', fn($id) => (new GestionComercialControlador())->eliminarRegistro('contactos', (int) $id), $mwEmpresa);

$enrutador->agregar('GET', '/app/vendedores', fn() => (new GestionComercialControlador())->moduloBase('vendedores'), $mwEmpresa);
$enrutador->agregar('GET', '/app/vendedores/exportar/excel', [GestionComercialControlador::class, 'exportarVendedoresExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/vendedores', fn() => (new GestionComercialControlador())->guardarModuloBase('vendedores'), $mwEmpresa);
$enrutador->agregar('GET', '/app/vendedores/ver/{id}', fn($id) => (new GestionComercialControlador())->verRegistro('vendedores', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/vendedores/editar/{id}', fn($id) => (new GestionComercialControlador())->editarRegistro('vendedores', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/vendedores/editar/{id}', fn($id) => (new GestionComercialControlador())->actualizarRegistro('vendedores', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/vendedores/eliminar/{id}', fn($id) => (new GestionComercialControlador())->eliminarRegistro('vendedores', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/categorias', fn() => (new GestionComercialControlador())->moduloBase('categorias'), $mwEmpresa);
$enrutador->agregar('GET', '/app/categorias/exportar/excel', [GestionComercialControlador::class, 'exportarCategoriasExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/categorias', fn() => (new GestionComercialControlador())->guardarModuloBase('categorias'), $mwEmpresa);
$enrutador->agregar('GET', '/app/categorias/ver/{id}', fn($id) => (new GestionComercialControlador())->verRegistro('categorias', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/categorias/editar/{id}', fn($id) => (new GestionComercialControlador())->editarRegistro('categorias', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/categorias/editar/{id}', fn($id) => (new GestionComercialControlador())->actualizarRegistro('categorias', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/categorias/eliminar/{id}', fn($id) => (new GestionComercialControlador())->eliminarRegistro('categorias', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/listas-precios', fn() => (new GestionComercialControlador())->moduloBase('listas-precios'), $mwEmpresa);
$enrutador->agregar('GET', '/app/listas-precios/precio-producto', [GestionComercialControlador::class, 'precioProducto'], $mwEmpresa);
$enrutador->agregar('GET', '/app/listas-precios/exportar/excel', [GestionComercialControlador::class, 'exportarListasPreciosExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/listas-precios', fn() => (new GestionComercialControlador())->guardarModuloBase('listas-precios'), $mwEmpresa);
$enrutador->agregar('GET', '/app/listas-precios/ver/{id}', fn($id) => (new GestionComercialControlador())->verRegistro('listas-precios', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/listas-precios/editar/{id}', fn($id) => (new GestionComercialControlador())->editarRegistro('listas-precios', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/listas-precios/editar/{id}', fn($id) => (new GestionComercialControlador())->actualizarRegistro('listas-precios', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/listas-precios/eliminar/{id}', fn($id) => (new GestionComercialControlador())->eliminarRegistro('listas-precios', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/seguimiento', [GestionComercialControlador::class, 'seguimiento'], $mwEmpresa);
$enrutador->agregar('GET', '/app/seguimiento/exportar/excel', [GestionComercialControlador::class, 'exportarSeguimientoExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/seguimiento', [GestionComercialControlador::class, 'guardarSeguimiento'], $mwEmpresa);
$enrutador->agregar('GET', '/app/seguimiento/ver/{id}', fn($id) => (new GestionComercialControlador())->verRegistro('seguimiento', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/seguimiento/editar/{id}', fn($id) => (new GestionComercialControlador())->editarRegistro('seguimiento', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/seguimiento/editar/{id}', fn($id) => (new GestionComercialControlador())->actualizarRegistro('seguimiento', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/seguimiento/eliminar/{id}', fn($id) => (new GestionComercialControlador())->eliminarRegistro('seguimiento', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/aprobaciones', [GestionComercialControlador::class, 'aprobaciones'], $mwEmpresa);
$enrutador->agregar('GET', '/app/aprobaciones/exportar/excel', [GestionComercialControlador::class, 'exportarAprobacionesExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/aprobaciones', [GestionComercialControlador::class, 'guardarAprobacion'], $mwEmpresa);
$enrutador->agregar('GET', '/app/aprobaciones/ver/{id}', fn($id) => (new GestionComercialControlador())->verRegistro('aprobaciones', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/aprobaciones/editar/{id}', fn($id) => (new GestionComercialControlador())->editarRegistro('aprobaciones', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/aprobaciones/editar/{id}', fn($id) => (new GestionComercialControlador())->actualizarRegistro('aprobaciones', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/aprobaciones/eliminar/{id}', fn($id) => (new GestionComercialControlador())->eliminarRegistro('aprobaciones', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/documentos', [DocumentosControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('POST', '/app/documentos', [DocumentosControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('GET', '/app/configuracion/envio-oc-html', [DocumentosControlador::class, 'ordenCompra'], $mwEmpresa);
$enrutador->agregar('POST', '/app/configuracion/envio-oc-html', [DocumentosControlador::class, 'ordenCompra'], $mwEmpresa);
$enrutador->agregar('GET', '/app/notificaciones', fn() => (new GestionComercialControlador())->moduloBase('notificaciones'), $mwEmpresa);
$enrutador->agregar('POST', '/app/notificaciones', fn() => (new GestionComercialControlador())->guardarModuloBase('notificaciones'), $mwEmpresa);
$enrutador->agregar('GET', '/app/notificaciones/ver/{id}', fn($id) => (new GestionComercialControlador())->verRegistro('notificaciones', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/notificaciones/editar/{id}', fn($id) => (new GestionComercialControlador())->editarRegistro('notificaciones', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/notificaciones/editar/{id}', fn($id) => (new GestionComercialControlador())->actualizarRegistro('notificaciones', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/notificaciones/eliminar/{id}', fn($id) => (new GestionComercialControlador())->eliminarRegistro('notificaciones', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/historial', fn() => (new GestionComercialControlador())->moduloBase('historial'), $mwEmpresa);
$enrutador->agregar('POST', '/app/historial', fn() => (new GestionComercialControlador())->guardarModuloBase('historial'), $mwEmpresa);
$enrutador->agregar('GET', '/app/historial/ver/{id}', fn($id) => (new GestionComercialControlador())->verRegistro('historial', (int) $id), $mwEmpresa);
$enrutador->agregar('GET', '/app/historial/editar/{id}', fn($id) => (new GestionComercialControlador())->editarRegistro('historial', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/historial/editar/{id}', fn($id) => (new GestionComercialControlador())->actualizarRegistro('historial', (int) $id), $mwEmpresa);
$enrutador->agregar('POST', '/app/historial/eliminar/{id}', fn($id) => (new GestionComercialControlador())->eliminarRegistro('historial', (int) $id), $mwEmpresa);



$enrutador->agregar('GET', '/app/inventario/recepciones', [InventarioControlador::class, 'recepciones'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/recepciones', [InventarioControlador::class, 'guardarRecepcion'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/recepciones/editar/{id}', [InventarioControlador::class, 'editarRecepcion'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/recepciones/editar/{id}', [InventarioControlador::class, 'actualizarRecepcion'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/recepciones/eliminar/{id}', [InventarioControlador::class, 'eliminarRecepcion'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/recepciones/ver/{id}', [InventarioControlador::class, 'verRecepcion'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/recepciones/imprimir/{id}', [InventarioControlador::class, 'imprimirRecepcion'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/recepciones/pdf/{id}', [InventarioControlador::class, 'descargarRecepcionPdf'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/recepciones/enviar/{id}', [InventarioControlador::class, 'enviarRecepcion'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/recepciones/exportar/excel', [InventarioControlador::class, 'exportarRecepcionesExcel'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ordenes-compra', [InventarioControlador::class, 'ordenesCompra'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/ordenes-compra', [InventarioControlador::class, 'guardarOrdenCompra'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ordenes-compra/editar/{id}', [InventarioControlador::class, 'editarOrdenCompra'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/ordenes-compra/editar/{id}', [InventarioControlador::class, 'actualizarOrdenCompra'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ordenes-compra/ver/{id}', [InventarioControlador::class, 'verOrdenCompra'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/ordenes-compra/estado/{id}', [InventarioControlador::class, 'cambiarEstadoOrdenCompra'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ordenes-compra/imprimir/{id}', [InventarioControlador::class, 'imprimirOrdenCompra'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ordenes-compra/pdf/{id}', [InventarioControlador::class, 'descargarOrdenCompraPdf'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/ordenes-compra/enviar/{id}', [InventarioControlador::class, 'enviarOrdenCompra'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ordenes-compra/exportar/excel', [InventarioControlador::class, 'exportarOrdenesCompraExcel'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ajustes', [InventarioControlador::class, 'ajustes'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/ajustes', [InventarioControlador::class, 'guardarAjuste'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ajustes/ver/{id}', [InventarioControlador::class, 'verAjuste'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/ajustes/exportar/excel', [InventarioControlador::class, 'exportarAjustesExcel'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/movimientos', [InventarioControlador::class, 'movimientos'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/movimientos/exportar/excel', [InventarioControlador::class, 'exportarMovimientosExcel'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/proveedores', [InventarioControlador::class, 'proveedores'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/proveedores', [InventarioControlador::class, 'guardarProveedor'], $mwEmpresa);
$enrutador->agregar('POST', '/app/inventario/proveedores/eliminar/{id}', [InventarioControlador::class, 'eliminarProveedor'], $mwEmpresa);
$enrutador->agregar('GET', '/app/inventario/proveedores/exportar/excel', [InventarioControlador::class, 'exportarProveedoresExcel'], $mwEmpresa);
$enrutador->agregar('GET', '/app/configuracion/correos-stock', [ConfiguracionControlador::class, 'correosStock'], $mwEmpresa);
$enrutador->agregar('POST', '/app/configuracion/correos-stock', [ConfiguracionControlador::class, 'correosStock'], $mwEmpresa);

$enrutador->agregar('GET', '/app/punto-venta', [PuntoVentaControlador::class, 'index'], $mwEmpresa);
$enrutador->agregar('POST', '/app/punto-venta/venta/guardar', [PuntoVentaControlador::class, 'guardarVenta'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/apertura-caja', [PuntoVentaControlador::class, 'aperturaCaja'], $mwEmpresa);
$enrutador->agregar('POST', '/app/punto-venta/apertura-caja', [PuntoVentaControlador::class, 'guardarAperturaCaja'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/cierre-caja', [PuntoVentaControlador::class, 'cierreCaja'], $mwEmpresa);
$enrutador->agregar('POST', '/app/punto-venta/cierre-caja', [PuntoVentaControlador::class, 'guardarCierreCaja'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/ventas', [PuntoVentaControlador::class, 'ventas'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/ventas/ver/{id}', [PuntoVentaControlador::class, 'verVenta'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/ventas/imprimir/{id}', [PuntoVentaControlador::class, 'imprimirVenta'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/cajas', [PuntoVentaControlador::class, 'cajas'], $mwEmpresa);
$enrutador->agregar('POST', '/app/punto-venta/cajas', [PuntoVentaControlador::class, 'guardarCaja'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/cajas/exportar/excel', [PuntoVentaControlador::class, 'exportarCajasExcel'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/cajas/ver/{id}', [PuntoVentaControlador::class, 'verCaja'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/cajas/editar/{id}', [PuntoVentaControlador::class, 'editarCaja'], $mwEmpresa);
$enrutador->agregar('POST', '/app/punto-venta/cajas/editar/{id}', [PuntoVentaControlador::class, 'actualizarCaja'], $mwEmpresa);
$enrutador->agregar('POST', '/app/punto-venta/cajas/eliminar/{id}', [PuntoVentaControlador::class, 'eliminarCaja'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/movimientos', [PuntoVentaControlador::class, 'movimientosCaja'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/movimientos/exportar/excel', [PuntoVentaControlador::class, 'exportarMovimientosCajaExcel'], $mwEmpresa);
$enrutador->agregar('POST', '/app/punto-venta/movimientos', [PuntoVentaControlador::class, 'guardarMovimientoCaja'], $mwEmpresa);
$enrutador->agregar('GET', '/app/punto-venta/configuracion', [PuntoVentaControlador::class, 'configuracion'], $mwEmpresa);
$enrutador->agregar('POST', '/app/punto-venta/configuracion', [PuntoVentaControlador::class, 'guardarConfiguracion'], $mwEmpresa);
