<h1 class="h5 mb-3">Pagos Flow</h1>
<div class="card p-3 mb-3"><form method="POST" action="<?= e(url('/admin/flow/pagos/crear')) ?>" class="row g-2 align-items-end"><?= csrf_campo() ?>
  <div class="col-md-4"><label class="form-label">Empresa</label><select class="form-select" name="empresa_id" required><?php foreach($empresas as $e): ?><option value="<?= (int)$e['id'] ?>"><?= e($e['nombre_comercial']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-3"><label class="form-label">Plan</label><select class="form-select" name="plan_id" required><?php foreach($planes as $p): ?><option value="<?= (int)$p['id'] ?>"><?= e($p['nombre']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-2"><label class="form-label">Frecuencia</label><select class="form-select" name="frecuencia"><option value="mensual">Mensual</option><option value="anual">Anual</option></select></div>
  <div class="col-md-3"><label class="form-label">Concepto</label><input class="form-control" name="concepto" value="Cobro administrativo"></div>
  <div class="col-md-2"><button class="btn btn-primary btn-sm w-100">Crear pago</button></div>
</form></div>
<form class="row g-2 mb-3" method="GET" action="<?= e(url('/admin/flow/pagos')) ?>"><div class="col-md-2"><input type="date" name="desde" class="form-control" value="<?= e($filtros['desde']) ?>"></div><div class="col-md-2"><input type="date" name="hasta" class="form-control" value="<?= e($filtros['hasta']) ?>"></div><div class="col-md-3"><select class="form-select" name="empresa_id"><option value="">Todas empresas</option><?php foreach($empresas as $e): ?><option value="<?= (int)$e['id'] ?>" <?= (string)$filtros['empresa_id']===(string)$e['id']?'selected':'' ?>><?= e($e['nombre_comercial']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><select class="form-select" name="estado"><option value="">Todos</option><?php foreach(['pendiente','aprobado','rechazado','anulado'] as $es): ?><option value="<?= e($es) ?>" <?= $filtros['estado']===$es?'selected':'' ?>><?= e($es) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><button class="btn btn-outline-primary w-100">Filtrar</button></div></form>
<div class="card"><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Empresa</th><th>Plan</th><th>Orden</th><th>Token</th><th>Monto</th><th>Estado</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>
<?php foreach($pagos as $p): ?><tr><td><?= e($p['empresa']) ?></td><td><?= e($p['plan'] ?? '-') ?></td><td><?= e($p['commerce_order']) ?></td><td><?= e($p['flow_token']) ?></td><td>$<?= number_format((float)$p['monto'],0,',','.') ?> <?= e($p['moneda']) ?></td><td><?= e($p['estado_local']) ?> / <?= e($p['estado_flow']) ?></td><td><?= e($p['fecha_creacion']) ?></td><td><?php if(!empty($p['flow_token'])): ?><form method="POST" action="<?= e(url('/admin/flow/pagos/sincronizar/' . urlencode((string)$p['flow_token']))) ?>"><?= csrf_campo() ?><button class="btn btn-sm btn-outline-primary">Consultar estado</button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></div>
