<h1 class="h5 mb-3">Suscripciones Flow</h1>
<div class="card p-3 mb-3"><form method="POST" action="<?= e(url('/admin/flow/suscripciones/crear')) ?>" class="row g-2 align-items-end"><?= csrf_campo() ?>
  <div class="col-md-4"><label class="form-label">Empresa</label><select class="form-select" name="empresa_id" required><?php foreach($empresas as $e): ?><option value="<?= (int)$e['id'] ?>"><?= e($e['nombre_comercial']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-3"><label class="form-label">Plan</label><select class="form-select" name="plan_id" required><?php foreach($planes as $p): ?><option value="<?= (int)$p['id'] ?>"><?= e($p['nombre']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-3"><label class="form-label">Cobro</label><select class="form-select" name="tipo_cobro"><option value="mensual">Mensual</option><option value="anual">Anual</option></select></div>
  <div class="col-md-2"><button class="btn btn-primary btn-sm w-100">Crear suscripción</button></div>
</form></div>
<div class="card"><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Empresa</th><th>Plan</th><th>Flow sub.</th><th>Tipo</th><th>Estado local</th><th>Estado Flow</th><th>Próx. renovación</th><th>Acciones</th></tr></thead><tbody>
<?php foreach($suscripciones as $s): ?><tr><td><?= e($s['empresa']) ?></td><td><?= e($s['plan']) ?></td><td><?= e($s['flow_subscription_id']) ?></td><td><?= e($s['tipo_cobro']) ?></td><td><?= e($s['estado_local']) ?></td><td><?= e($s['estado_flow']) ?></td><td><?= e($s['proxima_renovacion'] ?? '-') ?></td><td class="d-flex gap-1"><form method="POST" action="<?= e(url('/admin/flow/suscripciones/sincronizar/' . urlencode((string)$s['flow_subscription_id']))) ?>"><?= csrf_campo() ?><button class="btn btn-sm btn-outline-primary">Sincronizar</button></form><form method="POST" action="<?= e(url('/admin/flow/suscripciones/cancelar/' . urlencode((string)$s['flow_subscription_id']))) ?>" onsubmit="return confirm('¿Cancelar suscripción?')"><?= csrf_campo() ?><button class="btn btn-sm btn-outline-danger">Cancelar</button></form></td></tr><?php endforeach; ?>
</tbody></table></div></div>
