<h1 class="h4 mb-3">Ajustes de inventario</h1>
<div class="alert alert-info py-2 px-3 small">
  Usa este módulo para registrar correcciones manuales de stock y consultar su historial.
  Puedes filtrar por producto, tipo y rango de fechas, y exportar los resultados visibles a Excel.
</div>
<div class="card mb-3"><div class="card-header">Nuevo ajuste</div><div class="card-body">
<form method="POST" action="<?= e(url('/app/inventario/ajustes')) ?>" class="row g-2"><?= csrf_campo() ?>
<div class="col-md-4"><label class="form-label">Producto</label><select name="producto_id" class="form-select" required><option value="">Seleccionar...</option><?php foreach($productos as $p): ?><option value="<?= (int)$p['id'] ?>"><?= e($p['codigo'] . ' · ' . $p['nombre'] . ' (stock ' . number_format((float)$p['stock_actual'],2) . ')') ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="form-label">Tipo ajuste</label><select name="tipo_ajuste" class="form-select"><option value="entrada">Entrada</option><option value="salida">Salida</option></select></div>
<div class="col-md-2"><label class="form-label">Cantidad</label><input type="number" step="0.01" min="0" name="cantidad" class="form-control" required></div>
<div class="col-md-4"><label class="form-label">Motivo</label><select name="motivo" class="form-select"><?php foreach($motivos as $k=>$m): ?><option value="<?= e($k) ?>"><?= e($m) ?></option><?php endforeach; ?></select></div>
<div class="col-12"><label class="form-label">Observación</label><input name="observacion" class="form-control"></div>
<div class="col-12"><button class="btn btn-primary btn-sm">Guardar ajuste</button></div>
</form></div></div>

<div class="card"><div class="card-header d-flex justify-content-between align-items-center flex-wrap gap-2"><span>Historial de ajustes</span><a href="<?= e(url('/app/inventario/ajustes/exportar/excel?' . http_build_query($filtros ?? []))) ?>" class="<?= e(\Aplicacion\Servicios\ExcelExpoFormato::BOTON_CLASES) ?>" style="<?= e(\Aplicacion\Servicios\ExcelExpoFormato::BOTON_ESTILO) ?>"><?= e(\Aplicacion\Servicios\ExcelExpoFormato::BOTON_TEXTO) ?></a></div><div class="card-body border-bottom"><form method="GET" class="row g-2"><div class="col-md-3"><select name="producto_id" class="form-select form-select-sm"><option value="0">Todos los productos</option><?php foreach($productos as $p): ?><option value="<?= (int)$p['id'] ?>" <?= (int)($filtros['producto_id'] ?? 0)===(int)$p['id']?'selected':'' ?>><?= e($p['nombre']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><select name="tipo_ajuste" class="form-select form-select-sm"><option value="">Todos</option><option value="entrada" <?= ($filtros['tipo_ajuste'] ?? '')==='entrada'?'selected':'' ?>>Entrada</option><option value="salida" <?= ($filtros['tipo_ajuste'] ?? '')==='salida'?'selected':'' ?>>Salida</option></select></div><div class="col-md-2"><input type="date" name="fecha_desde" value="<?= e($filtros['fecha_desde'] ?? '') ?>" class="form-control form-control-sm"></div><div class="col-md-2"><input type="date" name="fecha_hasta" value="<?= e($filtros['fecha_hasta'] ?? '') ?>" class="form-control form-control-sm"></div><div class="col-md-3"><button class="btn btn-outline-secondary btn-sm">Filtrar</button></div></form></div>
<div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Fecha</th><th>Producto</th><th>Tipo</th><th>Cantidad</th><th>Motivo</th><th>Usuario</th><th class="text-end">Acción</th></tr></thead><tbody>
<?php if(empty($ajustes)): ?><tr><td colspan="7" class="text-center py-3 text-muted">Sin ajustes registrados.</td></tr><?php else: foreach($ajustes as $a): ?><tr><td><?= e($a['fecha_creacion']) ?></td><td><?= e(($a['codigo'] ?? '') . ' · ' . ($a['producto_nombre'] ?? '')) ?></td><td><?= e($a['tipo_ajuste']) ?></td><td><?= number_format((float)$a['cantidad'],2) ?></td><td><?= e($a['motivo']) ?></td><td><?= e($a['usuario_nombre'] ?? '-') ?></td><td class="text-end"><a class="btn btn-outline-secondary btn-sm" href="<?= e(url('/app/inventario/ajustes/ver/' . $a['id'])) ?>">Ver</a></td></tr><?php endforeach; endif; ?>
</tbody></table></div></div>
